---

- block:
    - validate:
        schema:
          type: object
          properties:
            kernel_ip_forwarding:
              type: boolean
              default: no
            ufw_manage_defaults:
              type: boolean
              default: no
          required:
            - kernel_ip_forwarding
            - ufw_manage_defaults
        instance: "{{ os }}"
      register: os_validated

    - set_fact:
        os_v: "{{ os_validated.result }}"

    - name: 'Harden operating system'
      import_role:
        name: dev-sec.os-hardening
      vars:
        ufw_manage_defaults: "{{ os_v.ufw_manage_defaults }}"
        sysctl_overwrite:
          net.ipv4.ip_forward: "{{ os_v.kernel_ip_forwarding | ternary(1, 0) }}"
#          ​net.ipv6.conf.all.accept_source_route: 0
#          ​net.ipv6.conf.default.accept_source_route: 0
#          ​net.ipv4.tcp_syncookies: 1
#          net.ipv4.tcp_max_syn_backlog: 2048
#          net.ipv4.tcp_synack_retries: 2
#          ​net.ipv4.tcp_syn_retries: 5

#    - name: "Prevent IP spoofing"
#      template:
#        src: host.conf.j2
#        dest: /etc/host.conf
#        mode: 644

#    - name: "Secure shared memory"
#      lineinfile:
#        path: /etc/fstab
#        line: tmpfs /run/shm tmpfs defaults,noexec,nosuid 0 0
#      register: reboot
  become: yes
  tags:
    - os_harden
