---

- block:
    - name: "Install git"
      apt:
        name: git
      become: yes

    - name: "Install pip3"
      shell: curl -sS https://bootstrap.pypa.io/get-pip.py | sudo python3
      args:
        creates: /usr/local/bin/pip3
        warn: no

    - name: "Install Ansible and dependencies"
      pip:
        name:
          - ansible
          - cryptography
          - deepmerge
          - git+git://github.com/Julian/jsonschema.git
          - google-api-python-client
        executable: /usr/local/bin/pip3
        extra_args: --upgrade --user
  tags:
    - os_install_ansible
