---

- block:
    - validate:
        schema:
          type: object
          additionalProperties:
            - command
        instance: "{{ os }}"
      register: os_validated

    - set_fact:
        os_v: "{{ os_validated.result }}"

    - name: "Install pip3"
      shell: curl -sS https://bootstrap.pypa.io/get-pip.py | sudo python3
      args:
        creates: /usr/local/bin/pip3
        warn: no
  tags:
    - os_install_pip3
