---

- block:
    - name: "Install git"
      apt:
        name: git
      become: yes

    - name: "Install pip3"
      shell: curl -sS https://bootstrap.pypa.io/get-pip.py | sudo python3
      warn: no

    - name: "Install Ansible and dependencies"
      command: >
        pip3 install --upgrade --user
          ansible
          cryptography
          git+git://github.com/Julian/jsonschema.git
  tags:
    - os_install_ansible
