---

- block:
    - name: "Install git"
      apt:
        name: git
      become: yes

    - name: "Install pip3"
      shell: curl -sS https://bootstrap.pypa.io/get-pip.py | sudo python3

    - name: "Install Ansible and dependencies"
      shell: >
        pip3 install --user
          ansible
          cryptography
          git+git://github.com/Julian/jsonschema.git

    - name: "Configure .bashrc"
      blockinfile:
        path: ~/.bashrc
        state: present
        marker: "# {mark} Ansible ansible"
        block: |
          alias gpl='git pull origin'
          alias gs='git status'
  tags:
    - ansible_install
