---

- block:
    - validate:
        schema:
          type: object
          properties:
            ssh_allowed_networks:
              type: array
              items:
                type: string
                format: ipv4
              minLength: 1
          required:
            - ssh_allowed_networks
        instance: "{{ os }}"
      register: os_validated

    - set_fact:
        os_v: "{{ os_validated.result }}"

    - block:
#        - name: "Wait for the lockfile to be released"
#          wait_for:
#            path: /var/lib/dpkg/lock-frontend
#            state: absent
#
        - name: "Install UFW and supporting packages"
          apt:
            name:
              - ufw
              - iptables-persistent
            state: present

        - name: "Set the default policy"
          template:
            dest: /etc/default/ufw
            src: ufw_default_policy.j2
            force: yes
            mode: 0644

        - name: "Create the /var/log/ufw.log file"
          copy:
            content: ""
            dest: /var/log/ufw.log
            force: no
            group: adm
            mode: 0644
            owner: syslog

        - name: "Add ssh rules"
          ufw:
            rule: allow
            from_ip: "{{ item }}"
            port: 22
            proto: tcp
          notify: os_ufw_rules_changed
          loop: "{{ os_v.ssh_allowed_networks }}"

        - name: "Allow localhost access to the local machine's ports"
          ufw:
            rule: allow
            from_ip: 127.0.0.1
            to_ip: 127.0.0.1
          notify: os_ufw_rules_changed

        - name: "Enable the firewall"
          ufw:
            state: enabled
          notify: os_ufw_rules_changed
      become: yes
  tags:
    - os_install_ufw
