---

- block:
    - validate:
        schema:
          type: object
          properties:
            command:
              type: string
              enum:
                - dependency
                - harden
                - reboot
                - reboot_if_required
                - shutdown
                - swap
                - unattended_upgrades_install
                - update_packages
                - upgrade_packages
                - ufw_install
          required:
            - command
        instance: "{{ os }}"

    - include_tasks: '{{ os.command }}.yml'
      when: os.command != 'dependency'
  tags:
    - os
