---

- block:
    - name: "Flush handlers before reboot"
      meta: flush_handlers

    - name: "Reboot machine"
      shell: nohup bash -c "sleep 2s && shutdown -r now" &
      become: yes

    - name: "Wait for the SSH connection to return"
      wait_for_connection:
        timeout: 240
        delay: 10
  tags:
    - os_reboot
