---

- block:
    - name: "Flush handlers before shutdown"
      meta: flush_handlers

    - name: "Shutdown the machine"
      shell: nohup bash -c "sleep 2s && shutdown now" &
      become: yes

    - name: "Wait for the machine to shutdown"
      wait_for:
        delay: 5
        host: "{{ inventory_hostname }}"
        port: 22
        state: stopped
      delegate_to: localhost
  tags:
    - os_shutdown
