---

- block:
    - name: "Flush handlers before shutdown"
      meta: flush_handlers

    - name: "Shutdown the machine"
      shell: nohup bash -c "sleep 2s && shutdown now" &
      become: yes
  tags:
    - os_shutdown
