---

- block:
    - validate:
        schema:
          type: object
          properties:
            device:
              type: string
            swappiness:
              type: integer
              minimum: 0
              maximum: 100
              default: 10
            cache_pressure:
              type: integer
              minimum: 0
              maximum: 100
              default: 50
          required:
            - device
        instance: "{{ os }}"
      register: os_validated

    - set_fact:
        os_v: "{{ os_validated.result }}"

    - block:
        - name: "Check if swap device is already enabled"
          command: "swapon --show"
          register: os_swap_device_check

        - block:
            - name: "Initialize {{ os_v.device }} as a swap device"
              command: "mkswap {{ os_v.device }}"

            - name: "Add {{ os_v.device }} to /etc/fstab"
              lineinfile:
                path: /etc/fstab
                line: "{{ os_v.device }} none swap sw 0 0"
          when: os_v.device not in os_swap_device_check.stdout

        - name: "Set swap swappiness"
          sysctl:
            name: vm.swappiness
            reload: yes
            state: present
            sysctl_set: yes
            value:  "{{ os_v.swappiness }}"

        - name: "Set swap cache pressure"
          sysctl:
            name: vm.vfs_cache_pressure
            reload: yes
            state: present
            sysctl_set: yes
            value:  "{{ os_v.cache_pressure }}"
      become: yes

  tags:
    - os_swap_device
