---

- name: os_reboot
  set_fact:
    os_reboot_required: yes

- block:
    - name: os_ufw_rules_changed
      shell: iptables-save > /etc/iptables/rules.v4

    - name: os_ufw_reload
      ufw:
        state: reloaded
      listen: os_ufw_rules_changed
  become: yes
